In [1]:
import pandas as pd
import numpy as mp

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import export_graphviz
import collections
#from PIL import Image

from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
#import pydotplus

from matplotlib import pyplot as plt
#import seaborn as sns

#import graphviz
#import pydotplus
import io
from scipy import misc

%matplotlib inline

c:\users\asus\appdata\local\programs\python\python36\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [2]:
data = pd.read_csv("final_filter.csv")

In [3]:
data.head()

location    mean_X    mean_Y    mean_Z     std_X     std_Y     std_Z  \
0         1 -0.023929  0.112579 -0.990092  0.157646  0.188360  0.101932   
1         1 -0.037360 -0.007463 -0.996015  0.090459  0.118507  0.076649   
2         1 -0.089317 -0.017025 -0.990883  0.091634  0.100888  0.082321   
3         1 -0.101585 -0.027065 -0.996976  0.092982  0.100444  0.078133   
4         1 -0.099574 -0.008085 -1.003562  0.076271  0.119020  0.059293   

     skew_X    skew_Y    skew_Z  label  
0 -0.443176  2.052829  0.103822     11  
1  0.666670 -0.122277  0.050711     11  
2 -0.565520 -0.045078  1.029924     11  
3 -0.378990 -0.160353 -0.628184     11  
4 -0.111909 -0.189929 -0.381072     11

In [4]:
features = data.columns
features

Index(['location', 'mean_X', 'mean_Y', 'mean_Z', 'std_X', 'std_Y', 'std_Z',
       'skew_X', 'skew_Y', 'skew_Z', 'label'],
      dtype='object')

In [5]:
features = [x for x in features if x != 'label']
features

['location',
 'mean_X',
 'mean_Y',
 'mean_Z',
 'std_X',
 'std_Y',
 'std_Z',
 'skew_X',
 'skew_Y',
 'skew_Z']

In [6]:
train, test = train_test_split(data, test_size = 0.07)
print(len(data))
print(len(train))
print(len(test))

3392
3154
238


In [7]:
dt= DecisionTreeClassifier(min_samples_split=100,criterion='entropy')

In [8]:
x_train = train[features]
y_train = train["label"]

x_test = test[features]
y_test = test["label"]

In [9]:
dt =dt.fit(x_train, y_train)

In [10]:
y_pred = dt.predict(x_test)

In [11]:

y_pred

array([13, 11, 14, 13, 14, 21, 21, 14, 11, 31, 12, 13, 12, 12, 22, 14, 21,
       12, 14, 13, 15, 12, 15, 31, 13, 21, 22, 15, 13, 22, 14, 11, 11, 15,
       21, 11, 12, 15, 15, 23, 14, 22, 12, 13, 11, 11, 11, 15, 11, 13, 14,
       15, 15, 12, 11, 12, 33, 21, 13, 33, 15, 31, 15, 33, 22, 11, 13, 12,
       11, 31, 15, 11, 15, 15, 11, 13, 11, 15, 14, 15, 33, 32, 13, 31, 15,
       11, 15, 21, 13, 21, 15, 31, 12, 11, 11, 21, 31, 12, 15, 14, 31, 11,
       21, 31, 31, 11, 33, 12, 22, 14, 21, 33, 14, 32, 11, 12, 22, 11, 21,
       12, 12, 12, 31, 12, 12, 13, 32, 11, 11, 12, 21, 13, 21, 15, 21, 21,
       21, 14, 14, 21, 23, 12, 11, 21, 33, 21, 31, 31, 15, 32, 12, 14, 14,
       33, 11, 11, 12, 12, 23, 13, 33, 12, 11, 13, 12, 13, 11, 22, 33, 15,
       23, 15, 14, 31, 13, 21, 23, 13, 21, 13, 13, 14, 15, 15, 15, 11, 13,
       33, 15, 21, 11, 31, 21, 21, 12, 31, 13, 14, 12, 31, 15, 11, 15, 15,
       21, 13, 33, 33, 11, 21, 15, 14, 13, 31, 11, 14, 14, 11, 15, 33, 12,
       21, 23, 31, 31, 31

In [12]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred) * 100
print("Accuracy using desicion Tree: ", score, "%" )

Accuracy using desicion Tree:  93.69747899159664 %


In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score,precision_score,recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve

c = confusion_matrix(y_test,y_pred)
f1 = f1_score(y_test,y_pred,average="micro")
p = precision_score(y_test, y_pred, average="macro")
r = recall_score(y_test,y_pred,average="macro")

print("F1 score: ", f1)
print("Precision: " , p)
print("recall: " , r)
print("\nconfusion matrix: \n" , c)

F1 score:  0.9369747899159664
Precision:  0.9356216608164076
recall:  0.9337608882345724

confusion matrix: 
 [[33  2  2  0  1  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0  0]
 [ 0  1 24  0  0  0  0  0  0  0  0]
 [ 3  0  0 23  0  0  0  0  0  0  0]
 [ 2  0  1  0 33  0  0  0  0  0  0]
 [ 0  0  0  0  0 32  0  0  0  0  0]
 [ 0  0  0  0  0  0  7  1  0  0  0]
 [ 0  0  0  0  0  0  1  5  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  0  4  0]
 [ 0  0  0  0  0  0  0  0  1  0 14]]
