In [1]:
import sklearn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
import numpy as mp

from sklearn.metrics import confusion_matrix, accuracy_score,f1_score,precision_score,recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve



from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB


In [2]:
data = pd.read_csv("final_filter.csv")

In [3]:
data.head()

location    mean_X    mean_Y    mean_Z     std_X     std_Y     std_Z  \
0         1 -0.023929  0.112579 -0.990092  0.157646  0.188360  0.101932   
1         1 -0.037360 -0.007463 -0.996015  0.090459  0.118507  0.076649   
2         1 -0.089317 -0.017025 -0.990883  0.091634  0.100888  0.082321   
3         1 -0.101585 -0.027065 -0.996976  0.092982  0.100444  0.078133   
4         1 -0.099574 -0.008085 -1.003562  0.076271  0.119020  0.059293   

     skew_X    skew_Y    skew_Z  label  
0 -0.443176  2.052829  0.103822     11  
1  0.666670 -0.122277  0.050711     11  
2 -0.565520 -0.045078  1.029924     11  
3 -0.378990 -0.160353 -0.628184     11  
4 -0.111909 -0.189929 -0.381072     11

In [4]:
features = data.columns
features

Index(['location', 'mean_X', 'mean_Y', 'mean_Z', 'std_X', 'std_Y', 'std_Z',
       'skew_X', 'skew_Y', 'skew_Z', 'label'],
      dtype='object')

In [5]:
features = [x for x in features if x != 'label']
features

['location',
 'mean_X',
 'mean_Y',
 'mean_Z',
 'std_X',
 'std_Y',
 'std_Z',
 'skew_X',
 'skew_Y',
 'skew_Z']

In [6]:
train, test = train_test_split(data, test_size = 0.07)
print(len(data))
print(len(train))
print(len(test))


3392
3154
238


In [7]:
x_train = train[features]
y_train = train["label"]

x_test = test[features]
y_test = test["label"]

In [8]:
Nb=GaussianNB()
Nb= Nb.fit(x_train,y_train)


In [9]:
y_pred=Nb.predict(x_test)


In [10]:
y_pred

array([21, 14, 33, 31, 23, 33, 33, 33, 12, 21, 31, 14, 15, 23, 21, 11, 14,
       21, 11, 21, 13, 22, 11, 11, 31, 33, 13, 14, 14, 11, 15, 15, 21, 11,
       31, 23, 21, 11, 21, 11, 11, 32, 11, 11, 14, 14, 15, 14, 33, 23, 21,
       14, 21, 11, 12, 31, 21, 11, 12, 12, 11, 33, 11, 11, 13, 11, 11, 12,
       11, 15, 33, 11, 22, 12, 11, 15, 15, 33, 15, 31, 33, 14, 11, 15, 12,
       31, 15, 15, 23, 23, 11, 15, 21, 11, 11, 13, 14, 21, 13, 12, 31, 12,
       14, 11, 21, 15, 31, 11, 33, 13, 11, 14, 13, 22, 22, 11, 32, 14, 31,
       21, 22, 21, 11, 15, 31, 13, 33, 11, 11, 11, 14, 22, 22, 23, 12, 14,
       21, 15, 21, 23, 14, 15, 14, 21, 14, 14, 11, 14, 21, 31, 33, 21, 21,
       13, 21, 12, 11, 13, 12, 12, 11, 11, 15, 11, 33, 12, 11, 31, 21, 31,
       13, 13, 11, 22, 15, 14, 14, 21, 14, 33, 33, 31, 13, 11, 14, 14, 14,
       31, 33, 11, 12, 33, 11, 31, 21, 15, 33, 13, 12, 14, 11, 15, 33, 11,
       31, 33, 21, 15, 21, 12, 21, 12, 15, 21, 13, 32, 33, 13, 21, 11, 33,
       15, 33, 12, 13, 15

In [11]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred) * 100
print("Accuracy using Naive Bayes: ", score, "%" )

Accuracy using Naive Bayes:  86.1344537815126 %


In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score,precision_score,recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve

c = confusion_matrix(y_test,y_pred)
f1 = f1_score(y_test,y_pred,average="micro")
p = precision_score(y_test, y_pred, average="macro")
r = recall_score(y_test,y_pred,average="macro")

print("F1 score: ", f1)
print("Precision: " , p)
print("recall: " , r)
print("\nconfusion matrix: \n" , c)

F1 score:  0.8613445378151261
Precision:  0.8826137810180363
recall:  0.8807534928465163

confusion matrix: 
 [[33  0  1  4  5  0  0  0  0  0  0]
 [ 0 20  0  0  4  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0  0]
 [ 2  0  0 25  0  0  0  0  0  0  0]
 [12  0  0  1 17  0  0  0  0  0  0]
 [ 0  0  0  0  0 34  0  0  0  0  0]
 [ 0  0  0  0  0  0  7  2  0  0  0]
 [ 0  0  0  0  0  0  1  6  0  0  0]
 [ 0  0  0  0  0  0  0  0 19  0  0]
 [ 0  0  0  0  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  1  0 24]]
