In [1]:
import sklearn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
import numpy as mp
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve
import itertools
%matplotlib inline
import matplotlib.pyplot as plt




from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

In [2]:
data = pd.read_csv("final_filter.csv")
#data.skew(axis = 0, skipna = True)

In [3]:
data.head()

location    mean_X    mean_Y    mean_Z     std_X     std_Y     std_Z  \
0         1 -0.023929  0.112579 -0.990092  0.157646  0.188360  0.101932   
1         1 -0.037360 -0.007463 -0.996015  0.090459  0.118507  0.076649   
2         1 -0.089317 -0.017025 -0.990883  0.091634  0.100888  0.082321   
3         1 -0.101585 -0.027065 -0.996976  0.092982  0.100444  0.078133   
4         1 -0.099574 -0.008085 -1.003562  0.076271  0.119020  0.059293   

     skew_X    skew_Y    skew_Z  label  
0 -0.443176  2.052829  0.103822     11  
1  0.666670 -0.122277  0.050711     11  
2 -0.565520 -0.045078  1.029924     11  
3 -0.378990 -0.160353 -0.628184     11  
4 -0.111909 -0.189929 -0.381072     11

In [4]:
features = data.columns
features

Index(['location', 'mean_X', 'mean_Y', 'mean_Z', 'std_X', 'std_Y', 'std_Z',
       'skew_X', 'skew_Y', 'skew_Z', 'label'],
      dtype='object')

In [5]:
features = [x for x in features if x != 'label']
features

['location',
 'mean_X',
 'mean_Y',
 'mean_Z',
 'std_X',
 'std_Y',
 'std_Z',
 'skew_X',
 'skew_Y',
 'skew_Z']

In [6]:
train, test = train_test_split(data, test_size = 0.07)
print(len(data))
print(len(train))
print(len(test))


3392
3154
238


In [7]:
x_train = train[features]
y_train = train["label"]

x_test = test[features]
y_test = test["label"]

In [8]:
#kf = KFold(n_splits = 5,shuffle=True,random_state=1)
#lr = LinearRegression()
#cv_scores = cross_val_score(lr,x_train,y_train,cv=kf)
#while i<=4:
#    cv_scores[i]

#    i+=1

In [9]:

#for i in cv_scores:
 #   train, test = train_test_split(data, test_size = cv_scores[i]
  #  len(data[i]) 
   # len(train[i])
    #len(test[i])     '''                          

In [10]:
x_train = train[features]
y_train = train["label"]

x_test = test[features]
y_test = test["label"]

In [11]:
NN=MLPClassifier(activation = 'relu', solver='adam', alpha=0.01,
                    hidden_layer_sizes=(50, 50), random_state=1)
NN= NN.fit(x_train,y_train)


c:\users\asus\appdata\local\programs\python\python36\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [12]:
y_pred=NN.predict(x_test)


In [13]:
y_pred

array([11, 23, 31, 21, 33, 15, 11, 13, 11, 11, 11, 11, 12, 11, 14, 31, 15,
       12, 15, 14, 21, 22, 21, 21, 15, 14, 22, 11, 11, 11, 13, 21, 11, 21,
       33, 15, 12, 15, 23, 33, 13, 31, 33, 15, 13, 12, 13, 14, 21, 33, 33,
       23, 14, 11, 31, 32, 21, 11, 12, 14, 21, 12, 32, 11, 15, 33, 11, 13,
       11, 23, 15, 11, 15, 33, 21, 21, 21, 15, 11, 22, 15, 13, 15, 13, 12,
       15, 22, 11, 15, 15, 11, 11, 13, 33, 12, 13, 31, 33, 21, 31, 14, 12,
       23, 12, 15, 21, 15, 12, 21, 15, 31, 33, 13, 21, 13, 33, 13, 15, 15,
       14, 15, 13, 31, 22, 12, 21, 15, 21, 33, 11, 15, 11, 11, 21, 21, 21,
       12, 11, 15, 31, 11, 21, 14, 12, 14, 22, 14, 31, 12, 14, 12, 11, 12,
       11, 31, 11, 11, 11, 11, 14, 11, 32, 14, 32, 13, 21, 11, 11, 33, 33,
       11, 11, 32, 13, 15, 31, 15, 13, 31, 12, 22, 31, 12, 14, 32, 21, 33,
       33, 14, 13, 21, 21, 22, 12, 14, 33, 15, 13, 22, 13, 33, 12, 15, 14,
       11, 14, 14, 23, 31, 31, 33, 11, 13, 14, 14, 12, 31, 14, 11, 31, 14,
       22, 31, 15, 33, 12

In [14]:
kf = KFold(n_splits = 5,shuffle=True,random_state=1)
lr = LinearRegression()
cv_scores = cross_val_score(lr,x_train,y_train,cv=kf)

In [15]:
from sklearn.metrics import accuracy_score
cv_scores = accuracy_score(y_test, y_pred) * 100
print("Accuracy using Neural Network: ", cv_scores, "%" )

Accuracy using Neural Network:  93.27731092436974 %


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score,precision_score,recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve

c = confusion_matrix(y_test,y_pred)
f1 = f1_score(y_test,y_pred,average="micro")
p = precision_score(y_test, y_pred, average="macro")
r = recall_score(y_test,y_pred,average="macro")

print("F1 score: ", f1)
print("Precision: " , p)
print("recall: " , r)
print("\nconfusion matrix: \n" , c)

F1 score:  0.9327731092436976
Precision:  0.9526437162246476
recall:  0.9441790235907882

confusion matrix: 
 [[32  0  0  0  3  0  0  0  0  0  0]
 [ 1 25  1  0  1  0  0  0  0  0  0]
 [ 1  0 20  0  0  0  0  0  0  0  0]
 [ 3  0  0 23  0  0  0  0  0  0  0]
 [ 4  0  0  1 29  0  0  0  0  0  0]
 [ 0  0  0  0  0 27  0  0  0  0  0]
 [ 0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  1  8  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0  0  0 22]]
