In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
from sklearn.model_selection import train_test_split
from IPython.display import Image 
import io
#import pydotplus
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier


%matplotlib inline

In [2]:
data = pd.read_csv("final_filter.csv")

In [3]:
data.head()

location    mean_X    mean_Y    mean_Z     std_X     std_Y     std_Z  \
0         1 -0.023929  0.112579 -0.990092  0.157646  0.188360  0.101932   
1         1 -0.037360 -0.007463 -0.996015  0.090459  0.118507  0.076649   
2         1 -0.089317 -0.017025 -0.990883  0.091634  0.100888  0.082321   
3         1 -0.101585 -0.027065 -0.996976  0.092982  0.100444  0.078133   
4         1 -0.099574 -0.008085 -1.003562  0.076271  0.119020  0.059293   

     skew_X    skew_Y    skew_Z  label  
0 -0.443176  2.052829  0.103822     11  
1  0.666670 -0.122277  0.050711     11  
2 -0.565520 -0.045078  1.029924     11  
3 -0.378990 -0.160353 -0.628184     11  
4 -0.111909 -0.189929 -0.381072     11

In [4]:
features = data.columns
features

Index(['location', 'mean_X', 'mean_Y', 'mean_Z', 'std_X', 'std_Y', 'std_Z',
       'skew_X', 'skew_Y', 'skew_Z', 'label'],
      dtype='object')

In [5]:
features = [x for x in features if x != 'label']
features

['location',
 'mean_X',
 'mean_Y',
 'mean_Z',
 'std_X',
 'std_Y',
 'std_Z',
 'skew_X',
 'skew_Y',
 'skew_Z']

In [6]:
train, test = train_test_split(data, test_size = 0.07)
print(len(data))
print(len(train))
print(len(test))

3392
3154
238


In [7]:
RF = RandomForestClassifier(n_estimators=100, max_depth=5,
                             random_state=0)


In [8]:
x_train = train[features]
y_train = train["label"]

x_test = test[features]
y_test = test["label"]

In [9]:
RF = RF.fit(x_train, y_train)

In [10]:
y_pred = RF.predict(x_test)

In [11]:
y_pred

array([12, 23, 12, 12, 12, 15, 21, 13, 21, 14, 15, 13, 12, 21, 14, 21, 11,
       14, 33, 11, 23, 15, 31, 14, 23, 31, 21, 11, 15, 21, 31, 22, 12, 21,
       14, 15, 13, 12, 11, 13, 12, 12, 11, 11, 33, 33, 14, 12, 11, 13, 21,
       15, 21, 33, 11, 22, 31, 21, 11, 11, 23, 11, 11, 33, 12, 21, 32, 13,
       11, 15, 31, 12, 31, 11, 31, 14, 33, 21, 11, 23, 14, 31, 14, 14, 11,
       32, 11, 21, 15, 15, 31, 13, 33, 12, 13, 11, 13, 21, 12, 21, 11, 11,
       14, 12, 15, 12, 14, 21, 12, 21, 11, 12, 14, 21, 12, 14, 31, 15, 11,
       22, 33, 32, 21, 11, 13, 11, 15, 11, 14, 13, 12, 33, 11, 15, 32, 21,
       33, 15, 31, 31, 22, 11, 11, 33, 21, 12, 13, 12, 23, 22, 14, 11, 33,
       14, 11, 14, 12, 11, 11, 11, 11, 12, 13, 11, 11, 14, 12, 14, 15, 13,
       15, 33, 31, 31, 15, 21, 32, 21, 14, 14, 15, 11, 13, 14, 33, 15, 11,
       11, 21, 11, 14, 33, 14, 11, 11, 12, 33, 31, 14, 33, 21, 21, 33, 33,
       12, 23, 31, 14, 21, 21, 33, 31, 31, 11, 21, 11, 22, 21, 22, 33, 15,
       13, 11, 14, 21, 15

In [12]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred) * 100
print("Accuracy using Random Forest Classifier: ", round(score, 1), "%" )

Accuracy using Random Forest Classifier:  90.3 %


In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score,precision_score,recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve

c = confusion_matrix(y_test,y_pred)
f1 = f1_score(y_test,y_pred,average="micro")
p = precision_score(y_test, y_pred, average="macro")
r = recall_score(y_test,y_pred,average="macro")

print("F1 score: ", f1)
print("Precision: " , p)
print("recall: " , r)
print("\nconfusion matrix: \n" , c)

F1 score:  0.903361344537815
Precision:  0.9151398157684425
recall:  0.9127985014307403

confusion matrix: 
 [[34  1  0  1  2  0  0  0  0  0  0]
 [ 0 25  0  0  0  0  0  0  0  0  0]
 [ 0  1 16  0  1  0  0  0  0  0  0]
 [ 3  0  0 26  0  0  0  0  0  0  0]
 [10  0  0  1 19  0  0  0  0  0  0]
 [ 0  0  0  0  0 35  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  3  8  0  0  0]
 [ 0  0  0  0  0  0  0  0 19  0  0]
 [ 0  0  0  0  0  0  0  0  0  5  0]
 [ 0  0  0  0  0  0  0  0  0  0 23]]
